// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quickbuy_Udemy.Repositorio.Contexto;

namespace Quickbuy_Udemy.Repositorio.Migrations
{
    [DbContext(typeof(QuickyBuy_Udemy_DB_Entity))]
    [Migration("20200404212914_migracao01")]
    partial class migracao01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<List<string>>("_mensagensValidacao")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(50);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDoEndereco")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PrevisaoDeEntrega")
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("_mensagensValidacao")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(50);

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("_mensagensValidacao")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(400);

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarhcar")
                        .HasMaxLength(256);

                    b.Property<List<string>>("_mensagensValidacao")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.ObjetoDeValor.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBoleto")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCartaoDeCredito")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeposito")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNaoDefinido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormaPagamentos");
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.ItemPedido", b =>
                {
                    b.HasOne("Quickbuy_Udemy.Dominio.Entity.Pedido", null)
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId");

                    b.HasOne("Quickbuy_Udemy.Dominio.Entity.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quickbuy_Udemy.Dominio.Entity.Pedido", b =>
                {
                    b.HasOne("Quickbuy_Udemy.Dominio.ObjetoDeValor.FormaPagamento", "formaDePagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quickbuy_Udemy.Dominio.Entity.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
